### ISSUE TITLE
В приниципе понравилось , но есть доеб

### ISSUE THREAD

**Issue by r6deadinside** [r6deadinside/yourhomework#1]
@ImSoHiGhZXC Почему ты использовал вместо свитч кейсов ифы ?

**Comment by ImSoHiGhZXC** [comment]
Ну мне показалось так удобнее

**Comment by r6deadinside** [comment]
Мне объяснить сегодня еще раз как это работает ?
# <img src="https://media.giphy.com/media/VgCDAzcKvsR6OM0uWg/giphy.gif" width="50">

**Comment by r6deadinside** [comment]
@ImSoHiGhZXC

**Comment by ImSoHiGhZXC** [comment]
возможно я просто не понял как оно точно работает, если не сложно то поясни плз

**Comment by r6deadinside** [comment]
```js
/* switch(x) {
    case 1: {
        console.log (1 + 1);
        break;
    }
    case 2: {}
    
    default: {
        console.log('выход');
    }
} */
```
